### ISSUE TITLE
Study 2 Motivated Intruder Test results

### ISSUE THREAD

**Issue by golankai** [maximilianmozes/textwash#10]
Hi, thanks so much for your work!
I was wondering if you could publish more fine results for the intruder test in study 2, as you did for study 1.
I am specifically interested in "which anonymized test was re-identified and which was safe".
Doesn't have to be per item, can also be statistical data, such percentage of de-anonymization success.

Would appreciate it a lot!
Kai.

**Comment by ben-aaron188** [comment]
Hi. Let me get back to this early next week. No problem with getting these
results to you.

**Comment by ben-aaron188** [comment]
Just going through this: this is not the info you're after? --> _"The mean de-anonymisation rate was 26.39% (SE = 1.34) with an average cosine similarity of 0.42 (SD = 0.39) between the actual person’s name and the participant’s input."_ (from section 4.2 in [https://arxiv.org/pdf/2208.13081.pdf](https://arxiv.org/pdf/2208.13081.pdf).

The per-item (=person) rates are in table 7.

We will update the paper + the Textwash tool very soon with improved models and more features. If you have any requests that we should report in the paper, let us know.

**Comment by golankai** [comment]
Hi, it is good but I am specifically interested in the de-anonymisation rate of **each description**.
Refering to this part: "_Each person was described in - on
average - 54 person descriptions (SD = 4.09)_.".
Thanks you very much!

**Comment by golankai** [comment]
Thank you :)

**Comment by golankai** [comment]
Hi, So I have a project in Uni to submit soon and would really like to have this data for it :)
Currently, I work with the data of Sduty 1 but it will enrich it by a lot!
Thanks a lot!

**Comment by ben-aaron188** [comment]
Here you go: https://www.dropbox.com/scl/fi/jadrhtskc5k2jr3mc8n8y/full_data_study2.csv?rlkey=c2tgh897li9syu93bee0j5490&dl=0
That link will do while we get that same file on the repo.

**Comment by ben-aaron188** [comment]
And also here now: https://github.com/maximilianmozes/textwash/blob/main/paper/study2/intruder_test/full_data_study2.csv

Would you mind sharing your uni project/thesis with us once it's done (no need to share here, email would do)?

**Comment by golankai** [comment]
yes! We still work on it but have a look
https://github.com/golankai/AMI/tree/main
