### ISSUE TITLE
Keyboard interrupt of a running process

### ISSUE THREAD

**Issue by MikeB2019x** [maximilianmozes/textwash#11]
After a straightforward cloning of the `textwash` repo and initial successful run of the examples, I discovered that if I do a keyboard interrupt of a running process (I tried some long files using `--cpu`), the next time I try to run `anon.py` I will get the following error:

```
(textwash) xxx@MAC-M1-16-FM73 textwash % python3 anon.py --input_dir examples --output_dir anonymised_examples --cpu
Some weights of BertForTokenClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Load input data from 'examples'
Traceback (most recent call last):
  File "/Users/xxx/git/textwash/anon.py", line 61, in <module>
    data[filename[: filename.index(".txt")]] = f.read().strip()
  File "/Users/xxx/opt/miniconda3/envs/textwash/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
(textwash) xxx@MAC-M1-16-FM73 textwash % file -I examples/*.txt                                                     
examples/kate_middleton.txt: text/plain; charset=utf-8     <----- NOTE FILE ENCODING IS CORRECT
```
Sometimes rebuilding my conda `textwash` environment resolves the problem but usually have to reclone the repo as well.

**Comment by ben-aaron188** [comment]
Thanks. We'll have a look. @maximilianmozes might be best placed to have a look.

**Comment by MikeB2019x** [comment]
Note that the error is happening on a file that has the correct encoding:
```
(textwash) xxx@MAC-M1-16-FM73 examples % file -I *.txt                                       
kate_middleton.txt: text/plain; charset=utf-8
```

**Comment by MikeB2019x** [comment]
yup the directories are correct.  I'm thinking something in the environment must have gone wrong.  The pattern I see is:
1. If I clone/reclone the repo and build the environment from scratch, everything works; until
1. if I try to run a large file any interruption will yield the error on restart.  The error will then persist even if I try to rerun the examples and even if I rebuild.

Note that the large file is 21MB.  I have not had a successful run even after 7 hours of processing.

**Comment by ben-aaron188** [comment]
Excellent. We’ll fix this.

**Comment by maximilianmozes** [comment]
Thanks @MikeB2019x! I've added this in now, main branch will be updated soon. :)
