### ISSUE TITLE
Error by running software

### ISSUE THREAD

**Issue by wsqvw** [maximilianmozes/textwash#7]
Hi,
I got this error while running the software:

FileNotFoundError: [Errno 2] No such file or directory: './data/model.pth'

Could you please help me with this issue?
Thanks in advance.

**Comment by ben-aaron188** [comment]
Hi -
Just as a quick check: did you download the `model.pth` file?
See the [first paragraph](https://github.com/maximilianmozes/textwash#quick-start-guide) in the quick start guide. 
If you have downloaded it and it still does not find the file, let us know and please share the code you used so we can replicate your error.
