### ISSUE TITLE
Google Colab integration

### ISSUE THREAD

**Issue by samux87** [maximilianmozes/textwash#8]
Hi,

I'm trying to use Textwash inside a Colab notebook but I having a lot of issues setting the environment; did you use it in a Colab NB in the past?

Thank you,
Samuele.

**Comment by maximilianmozes** [comment]
Hi, we have never used the library inside a Colab. Which issues are you having?

**Comment by samux87** [comment]
The first issue that I have is when I do 
`!pip install -r /content/textwash/requirements.txt`
I get
`ERROR: Could not find a version that satisfies the requirement torch==1.9.0 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.9.0`

Could Torch 1.11.0 work anyway?

Thanks,
Samuele.

**Comment by maximilianmozes** [comment]
I haven't tried running it with another version I'm afraid, so can't really say if it would work.
